import {
  Bot,
  ClipboardList,
  Cog,
  FileText,
  HeartPulse,
  Search,
  ShieldCheck,
  Upload,
  Wrench,
} from "lucide-react";

import { APP_ROUTES } from "@/lib/auth/routes";
import type { ExecutiveDashboardData } from "@/types/dashboard";

export const EXECUTIVE_DASHBOARD_DATA: ExecutiveDashboardData = {
  facilityName: "Northfield Refinery Complex",
  lastUpdated: "2026-07-01T08:45:00Z",
  kpis: [
    {
      id: "total-documents",
      title: "Total Documents",
      value: "14,382",
      change: "+312 indexed this month",
      changeType: "positive",
      icon: FileText,
    },
    {
      id: "industrial-assets",
      title: "Industrial Assets",
      value: "2,847",
      change: "Across 18 production units",
      changeType: "neutral",
      icon: Cog,
    },
    {
      id: "compliance-score",
      title: "Compliance Score",
      value: "97.4%",
      change: "5 items pending review",
      changeType: "warning",
      icon: ShieldCheck,
    },
    {
      id: "pending-maintenance",
      title: "Pending Maintenance",
      value: "34",
      change: "8 overdue tasks",
      changeType: "negative",
      icon: Wrench,
    },
    {
      id: "open-work-orders",
      title: "Open Work Orders",
      value: "127",
      change: "23 critical priority",
      changeType: "warning",
      icon: ClipboardList,
    },
    {
      id: "system-health",
      title: "System Health",
      value: "99.7%",
      change: "All subsystems nominal",
      changeType: "positive",
      icon: HeartPulse,
    },
  ],
  recentDocuments: [
    {
      id: "doc-1",
      title: "P&ID — Crude Distillation Unit 01",
      type: "Engineering Drawing",
      unit: "CDU-01",
      updatedAt: "2026-07-01T07:12:00Z",
      status: "indexed",
    },
    {
      id: "doc-2",
      title: "SOP — Pump P-4102 Seal Replacement",
      type: "Standard Procedure",
      unit: "Utilities",
      updatedAt: "2026-06-30T16:40:00Z",
      status: "indexed",
    },
    {
      id: "doc-3",
      title: "Inspection Report — Heat Exchanger E-2201",
      type: "Inspection Report",
      unit: "Reforming",
      updatedAt: "2026-06-30T11:05:00Z",
      status: "review",
    },
    {
      id: "doc-4",
      title: "OEM Manual — Centrifugal Compressor K-301",
      type: "OEM Manual",
      unit: "Hydrogen Plant",
      updatedAt: "2026-06-29T09:22:00Z",
      status: "indexed",
    },
    {
      id: "doc-5",
      title: "Incident Report — Unit 4 Flare Event",
      type: "Incident Report",
      unit: "Flare Systems",
      updatedAt: "2026-06-28T14:18:00Z",
      status: "processing",
    },
  ],
  recentActivity: [
    {
      id: "act-1",
      action: "Document indexed",
      subject: "API 510 Vessel Inspection — V-1204",
      actor: "System Pipeline",
      timestamp: "2026-07-01T08:30:00Z",
      type: "document",
    },
    {
      id: "act-2",
      action: "Work order assigned",
      subject: "WO-8842 — Cooling Water Pump Overhaul",
      actor: "Maria Chen",
      timestamp: "2026-07-01T07:55:00Z",
      type: "maintenance",
    },
    {
      id: "act-3",
      action: "Compliance review completed",
      subject: "LOTO Procedure Audit — CDU-01",
      actor: "James Okonkwo",
      timestamp: "2026-07-01T06:20:00Z",
      type: "compliance",
    },
    {
      id: "act-4",
      action: "Semantic search executed",
      subject: '"Flare stack maintenance history Unit 4"',
      actor: "David Reyes",
      timestamp: "2026-06-30T22:10:00Z",
      type: "search",
    },
    {
      id: "act-5",
      action: "Asset tag linked",
      subject: "P-4102 → 14 maintenance records",
      actor: "Knowledge Graph",
      timestamp: "2026-06-30T18:45:00Z",
      type: "system",
    },
    {
      id: "act-6",
      action: "Document uploaded",
      subject: "Turnaround Scope — Q3 2026",
      actor: "Sarah Mitchell",
      timestamp: "2026-06-30T15:30:00Z",
      type: "document",
    },
  ],
  complianceMetrics: [
    {
      id: "comp-1",
      standard: "OSHA 1910.147 — LOTO",
      score: 100,
      status: "compliant",
    },
    {
      id: "comp-2",
      standard: "API 510 — Pressure Vessels",
      score: 96,
      status: "compliant",
      dueDate: "2026-08-15",
    },
    {
      id: "comp-3",
      standard: "ISO 45001 — Safety Management",
      score: 98,
      status: "compliant",
    },
    {
      id: "comp-4",
      standard: "EPA SPCC — Spill Prevention",
      score: 94,
      status: "review",
      dueDate: "2026-07-20",
    },
    {
      id: "comp-5",
      standard: "Internal SOP Audit Cycle",
      score: 99,
      status: "compliant",
    },
    {
      id: "comp-6",
      standard: "NFPA 70E — Electrical Safety",
      score: 91,
      status: "at-risk",
      dueDate: "2026-07-10",
    },
  ],
  assetCategories: [
    {
      id: "cat-1",
      label: "Rotating Equipment",
      count: 847,
      percentage: 29.8,
      color: "var(--chart-1)",
    },
    {
      id: "cat-2",
      label: "Static Equipment",
      count: 612,
      percentage: 21.5,
      color: "var(--chart-2)",
    },
    {
      id: "cat-3",
      label: "Piping & Valves",
      count: 576,
      percentage: 20.2,
      color: "var(--chart-3)",
    },
    {
      id: "cat-4",
      label: "Instrumentation",
      count: 423,
      percentage: 14.9,
      color: "var(--accent-steel-muted)",
    },
    {
      id: "cat-5",
      label: "Electrical Systems",
      count: 389,
      percentage: 13.6,
      color: "var(--chart-4)",
    },
  ],
  recentSearches: [
    {
      id: "search-1",
      query: "P-4102 seal replacement procedure",
      results: 12,
      timestamp: "2026-07-01T08:15:00Z",
      user: "David Reyes",
    },
    {
      id: "search-2",
      query: "CDU furnace tube inspection interval",
      results: 8,
      timestamp: "2026-06-30T19:42:00Z",
      user: "Maria Chen",
    },
    {
      id: "search-3",
      query: "Flare stack maintenance history Unit 4",
      results: 15,
      timestamp: "2026-06-30T14:08:00Z",
      user: "James Okonkwo",
    },
    {
      id: "search-4",
      query: "API 653 tank inspection checklist",
      results: 6,
      timestamp: "2026-06-29T10:33:00Z",
      user: "Sarah Mitchell",
    },
  ],
  quickActions: [
    {
      id: "qa-1",
      label: "Upload Document",
      description: "Ingest new technical records",
      href: APP_ROUTES.documentsUpload,
      icon: Upload,
    },
    {
      id: "qa-2",
      label: "View Maintenance",
      description: "Review open work orders",
      href: APP_ROUTES.maintenance,
      icon: Wrench,
    },
    {
      id: "qa-3",
      label: "Compliance Check",
      description: "Run standards audit",
      href: APP_ROUTES.compliance,
      icon: ShieldCheck,
    },
    {
      id: "qa-4",
      label: "Ask Copilot",
      description: "Natural language queries",
      href: APP_ROUTES.copilot,
      icon: Bot,
    },
    {
      id: "qa-5",
      label: "Asset Registry",
      description: "Browse equipment tags",
      href: APP_ROUTES.assets,
      icon: Cog,
    },
    {
      id: "qa-6",
      label: "Semantic Search",
      description: "Search knowledge base",
      href: APP_ROUTES.search,
      icon: Search,
    },
  ],
  notifications: [
    {
      id: "notif-1",
      title: "Compliance review due",
      message: "NFPA 70E electrical safety audit due in 9 days for Unit 2.",
      timestamp: "2026-07-01T08:00:00Z",
      priority: "high",
      read: false,
    },
    {
      id: "notif-2",
      title: "Work order overdue",
      message: "WO-8842 cooling water pump overhaul is 2 days past scheduled date.",
      timestamp: "2026-07-01T06:30:00Z",
      priority: "high",
      read: false,
    },
    {
      id: "notif-3",
      title: "Documents indexed",
      message: "47 documents from Q3 turnaround package successfully indexed.",
      timestamp: "2026-06-30T22:00:00Z",
      priority: "low",
      read: true,
    },
    {
      id: "notif-4",
      title: "Inspection scheduled",
      message: "API 510 vessel inspection for V-1204 scheduled for Jul 8.",
      timestamp: "2026-06-30T14:15:00Z",
      priority: "medium",
      read: true,
    },
    {
      id: "notif-5",
      title: "System maintenance window",
      message: "Planned index rebuild Jul 5, 02:00–04:00 UTC. Search may be delayed.",
      timestamp: "2026-06-29T09:00:00Z",
      priority: "low",
      read: true,
    },
  ],
};
