import type {
  AssetHierarchyNode,
  AuditLogEntry,
  AuditSummaryItem,
  ComplianceStandard,
  IndustrialAsset,
  SopDocument,
  UpcomingMaintenance,
  WorkOrder,
} from "@/types/operations";

export const INDUSTRIAL_ASSETS: IndustrialAsset[] = [
  {
    id: "a-001",
    tag: "P-4102",
    name: "Cooling Water Circulation Pump",
    equipmentType: "Centrifugal Pump",
    location: "Utilities — Pump House 2",
    unit: "Utilities",
    healthStatus: "degraded",
    maintenanceDue: "Overdue by 2 days",
    maintenanceDueDate: "2026-06-29",
    criticality: "high",
  },
  {
    id: "a-002",
    tag: "E-2201",
    name: "Reformer Feed/Effluent Exchanger",
    equipmentType: "Heat Exchanger",
    location: "Reforming — Unit 2",
    unit: "Reforming",
    healthStatus: "healthy",
    maintenanceDue: "Jul 12, 2026",
    maintenanceDueDate: "2026-07-12",
    criticality: "high",
  },
  {
    id: "a-003",
    tag: "V-1204",
    name: "HP Separator Vessel",
    equipmentType: "Pressure Vessel",
    location: "CDU-01 — Fractionation",
    unit: "CDU-01",
    healthStatus: "healthy",
    maintenanceDue: "Jul 8, 2026",
    maintenanceDueDate: "2026-07-08",
    criticality: "high",
  },
  {
    id: "a-004",
    tag: "K-301",
    name: "Hydrogen Recycle Compressor",
    equipmentType: "Compressor",
    location: "Hydrogen Plant — Compression",
    unit: "Hydrogen Plant",
    healthStatus: "critical",
    maintenanceDue: "Due today",
    maintenanceDueDate: "2026-07-01",
    criticality: "high",
  },
  {
    id: "a-005",
    tag: "FV-1180",
    name: "Furnace Fuel Gas Control Valve",
    equipmentType: "Control Valve",
    location: "CDU-01 — Furnace Area",
    unit: "CDU-01",
    healthStatus: "healthy",
    maintenanceDue: "Aug 3, 2026",
    maintenanceDueDate: "2026-08-03",
    criticality: "medium",
  },
  {
    id: "a-006",
    tag: "F-101",
    name: "Crude Furnace",
    equipmentType: "Furnace",
    location: "CDU-01 — Heater Deck",
    unit: "CDU-01",
    healthStatus: "degraded",
    maintenanceDue: "Jul 5, 2026",
    maintenanceDueDate: "2026-07-05",
    criticality: "high",
  },
  {
    id: "a-007",
    tag: "T-401",
    name: "Crude Storage Tank",
    equipmentType: "Storage Tank",
    location: "Tank Farm — Area B",
    unit: "Tank Farm",
    healthStatus: "healthy",
    maintenanceDue: "Sep 14, 2026",
    maintenanceDueDate: "2026-09-14",
    criticality: "medium",
  },
  {
    id: "a-008",
    tag: "FLARE-04",
    name: "Unit 4 Elevated Flare Stack",
    equipmentType: "Flare Stack",
    location: "Flare Systems — Unit 4",
    unit: "Flare Systems",
    healthStatus: "healthy",
    maintenanceDue: "Jul 18, 2026",
    maintenanceDueDate: "2026-07-18",
    criticality: "high",
  },
  {
    id: "a-009",
    tag: "P-2208",
    name: "Boiler Feed Water Pump",
    equipmentType: "Centrifugal Pump",
    location: "Utilities — BFW Header",
    unit: "Utilities",
    healthStatus: "healthy",
    maintenanceDue: "Jul 22, 2026",
    maintenanceDueDate: "2026-07-22",
    criticality: "medium",
  },
  {
    id: "a-010",
    tag: "V-3301",
    name: "Amine Contactor Vessel",
    equipmentType: "Pressure Vessel",
    location: "Gas Treating — Unit 3",
    unit: "Gas Treating",
    healthStatus: "offline",
    maintenanceDue: "In turnaround",
    maintenanceDueDate: "2026-07-15",
    criticality: "high",
  },
];

export const ASSET_HIERARCHY: AssetHierarchyNode[] = [
  {
    id: "site-1",
    name: "Northfield Refinery Complex",
    type: "site",
    assetCount: 2847,
    children: [
      {
        id: "unit-cdu",
        name: "Crude Distillation Unit 01",
        type: "unit",
        assetCount: 412,
        healthStatus: "degraded",
        children: [
          {
            id: "sys-cdu-furnace",
            name: "Furnace & Feed System",
            type: "system",
            assetCount: 86,
            children: [
              { id: "eq-f101", name: "Crude Furnace F-101", type: "equipment", tag: "F-101", healthStatus: "degraded" },
              { id: "eq-fv1180", name: "Fuel Gas Valve FV-1180", type: "equipment", tag: "FV-1180", healthStatus: "healthy" },
            ],
          },
          {
            id: "sys-cdu-fract",
            name: "Fractionation Section",
            type: "system",
            assetCount: 124,
            children: [
              { id: "eq-v1204", name: "HP Separator V-1204", type: "equipment", tag: "V-1204", healthStatus: "healthy" },
            ],
          },
        ],
      },
      {
        id: "unit-h2",
        name: "Hydrogen Plant",
        type: "unit",
        assetCount: 318,
        healthStatus: "critical",
        children: [
          {
            id: "sys-h2-comp",
            name: "Compression Train",
            type: "system",
            assetCount: 54,
            children: [
              { id: "eq-k301", name: "Recycle Compressor K-301", type: "equipment", tag: "K-301", healthStatus: "critical" },
            ],
          },
        ],
      },
      {
        id: "unit-util",
        name: "Utilities",
        type: "unit",
        assetCount: 276,
        healthStatus: "degraded",
        children: [
          {
            id: "sys-util-pumps",
            name: "Cooling Water & BFW Pumps",
            type: "system",
            assetCount: 42,
            children: [
              { id: "eq-p4102", name: "CW Pump P-4102", type: "equipment", tag: "P-4102", healthStatus: "degraded" },
              { id: "eq-p2208", name: "BFW Pump P-2208", type: "equipment", tag: "P-2208", healthStatus: "healthy" },
            ],
          },
        ],
      },
      {
        id: "unit-flare",
        name: "Flare Systems",
        type: "unit",
        assetCount: 89,
        healthStatus: "healthy",
        children: [
          {
            id: "sys-flare-4",
            name: "Unit 4 Flare",
            type: "system",
            assetCount: 18,
            children: [
              { id: "eq-flare04", name: "Elevated Flare FLARE-04", type: "equipment", tag: "FLARE-04", healthStatus: "healthy" },
            ],
          },
        ],
      },
    ],
  },
];

export const UPCOMING_MAINTENANCE: UpcomingMaintenance[] = [
  {
    id: "um-1",
    assetTag: "K-301",
    assetName: "Hydrogen Recycle Compressor",
    task: "Vibration analysis & bearing inspection",
    scheduledDate: "2026-07-01T08:00:00Z",
    type: "predictive",
    assignedTo: "David Reyes",
  },
  {
    id: "um-2",
    assetTag: "V-1204",
    assetName: "HP Separator Vessel",
    task: "API 510 external inspection",
    scheduledDate: "2026-07-08T06:00:00Z",
    type: "preventive",
    assignedTo: "James Okonkwo",
  },
  {
    id: "um-3",
    assetTag: "F-101",
    assetName: "Crude Furnace",
    task: "Tube skin thermocouple calibration",
    scheduledDate: "2026-07-05T14:00:00Z",
    type: "preventive",
    assignedTo: "Maria Chen",
  },
  {
    id: "um-4",
    assetTag: "P-4102",
    assetName: "Cooling Water Circulation Pump",
    task: "Mechanical seal replacement",
    scheduledDate: "2026-06-29T06:00:00Z",
    type: "corrective",
    assignedTo: "Robert Singh",
  },
  {
    id: "um-5",
    assetTag: "FLARE-04",
    assetName: "Unit 4 Elevated Flare Stack",
    task: "Pilot burner & ignition system check",
    scheduledDate: "2026-07-18T09:00:00Z",
    type: "preventive",
    assignedTo: "Lisa Park",
  },
  {
    id: "um-6",
    assetTag: "T-401",
    assetName: "Crude Storage Tank",
    task: "API 653 floor thickness survey",
    scheduledDate: "2026-09-14T07:00:00Z",
    type: "preventive",
    assignedTo: "James Okonkwo",
  },
];

export const WORK_ORDERS: WorkOrder[] = [
  {
    id: "wo-1",
    woNumber: "WO-8842",
    title: "Cooling water pump overhaul",
    assetTag: "P-4102",
    priority: "critical",
    status: "overdue",
    assignedTo: "Maria Chen",
    dueDate: "2026-06-29",
    department: "Maintenance",
  },
  {
    id: "wo-2",
    woNumber: "WO-8917",
    title: "Compressor vibration mitigation",
    assetTag: "K-301",
    priority: "critical",
    status: "in_progress",
    assignedTo: "David Reyes",
    dueDate: "2026-07-02",
    department: "Reliability",
  },
  {
    id: "wo-3",
    woNumber: "WO-8934",
    title: "Furnace tube inspection prep",
    assetTag: "F-101",
    priority: "high",
    status: "scheduled",
    assignedTo: "Robert Singh",
    dueDate: "2026-07-05",
    department: "Operations",
  },
  {
    id: "wo-4",
    woNumber: "WO-8951",
    title: "HP separator isolation valve test",
    assetTag: "V-1204",
    priority: "high",
    status: "open",
    assignedTo: "James Okonkwo",
    dueDate: "2026-07-08",
    department: "Maintenance",
  },
  {
    id: "wo-5",
    woNumber: "WO-8968",
    title: "Flare pilot system maintenance",
    assetTag: "FLARE-04",
    priority: "medium",
    status: "scheduled",
    assignedTo: "Lisa Park",
    dueDate: "2026-07-18",
    department: "HSE",
  },
  {
    id: "wo-6",
    woNumber: "WO-8980",
    title: "BFW pump alignment check",
    assetTag: "P-2208",
    priority: "low",
    status: "open",
    assignedTo: "Maria Chen",
    dueDate: "2026-07-22",
    department: "Maintenance",
  },
  {
    id: "wo-7",
    woNumber: "WO-8721",
    title: "Amine contactor internal inspection",
    assetTag: "V-3301",
    priority: "high",
    status: "in_progress",
    assignedTo: "David Reyes",
    dueDate: "2026-07-15",
    department: "Turnaround",
  },
  {
    id: "wo-8",
    woNumber: "WO-8650",
    title: "Fuel gas valve actuator calibration",
    assetTag: "FV-1180",
    priority: "medium",
    status: "completed",
    assignedTo: "Robert Singh",
    dueDate: "2026-06-20",
    department: "Instrumentation",
  },
];

export const COMPLIANCE_STANDARDS: ComplianceStandard[] = [
  {
    id: "std-factory",
    name: "Factories Act, 1948 & State Rules",
    shortName: "Factory Act",
    score: 96,
    status: "compliant",
    lastAudit: "2026-03-15",
    nextAudit: "2026-09-15",
    openFindings: 2,
  },
  {
    id: "std-oisd",
    name: "OISD Standards (Oil Industry Safety Directorate)",
    shortName: "OISD",
    score: 94,
    status: "review",
    lastAudit: "2026-04-22",
    nextAudit: "2026-10-22",
    openFindings: 4,
  },
  {
    id: "std-peso",
    name: "PESO — Petroleum & Explosives Safety",
    shortName: "PESO",
    score: 98,
    status: "compliant",
    lastAudit: "2026-02-10",
    nextAudit: "2026-08-10",
    openFindings: 1,
  },
  {
    id: "std-iso",
    name: "ISO 45001 — Occupational Health & Safety",
    shortName: "ISO",
    score: 97,
    status: "compliant",
    lastAudit: "2026-05-08",
    nextAudit: "2026-11-08",
    openFindings: 1,
  },
];

export const COMPLIANCE_SCORE = 96.2;

export const AUDIT_SUMMARY: AuditSummaryItem[] = [
  {
    id: "aud-1",
    auditName: "Q2 OISD-STD-118 Storage Tank Audit",
    standard: "OISD",
    auditor: "External — SafePetro Consultants",
    completedAt: "2026-04-22",
    score: 94,
    findings: 4,
    status: "conditional",
  },
  {
    id: "aud-2",
    auditName: "ISO 45001 Surveillance Audit",
    standard: "ISO",
    auditor: "Bureau Veritas",
    completedAt: "2026-05-08",
    score: 97,
    findings: 1,
    status: "passed",
  },
  {
    id: "aud-3",
    auditName: "Factory Act Compliance Inspection",
    standard: "Factory Act",
    auditor: "State Factory Inspectorate",
    completedAt: "2026-03-15",
    score: 96,
    findings: 2,
    status: "passed",
  },
  {
    id: "aud-4",
    auditName: "PESO Pressure Vessel Certification Review",
    standard: "PESO",
    auditor: "PESO Regional Office",
    completedAt: "2026-02-10",
    score: 98,
    findings: 1,
    status: "passed",
  },
  {
    id: "aud-5",
    auditName: "NFPA 70E Electrical Safety Gap Assessment",
    standard: "ISO",
    auditor: "Internal HSE Team",
    completedAt: "2026-06-12",
    score: 91,
    findings: 6,
    status: "conditional",
  },
];

export const SOP_LIBRARY: SopDocument[] = [
  {
    id: "sop-1",
    code: "SOP-OPS-0142",
    title: "Crude Unit Startup Procedure",
    category: "Operations",
    version: "v6.1",
    department: "Operations",
    approvedBy: "Robert Singh",
    lastReviewed: "2026-05-20",
    status: "active",
  },
  {
    id: "sop-2",
    code: "SOP-MNT-0088",
    title: "Centrifugal Pump Seal Replacement",
    category: "Maintenance",
    version: "v3.4",
    department: "Maintenance",
    approvedBy: "Maria Chen",
    lastReviewed: "2026-06-10",
    status: "active",
  },
  {
    id: "sop-3",
    code: "SOP-HSE-0031",
    title: "Lockout/Tagout (LOTO) Procedure",
    category: "Safety",
    version: "v5.0",
    department: "HSE",
    approvedBy: "Lisa Park",
    lastReviewed: "2026-04-01",
    status: "active",
  },
  {
    id: "sop-4",
    code: "SOP-INS-0024",
    title: "API 510 Pressure Vessel Inspection",
    category: "Inspection",
    version: "v2.2",
    department: "Reliability",
    approvedBy: "James Okonkwo",
    lastReviewed: "2026-03-18",
    status: "review",
  },
  {
    id: "sop-5",
    code: "SOP-OPS-0201",
    title: "Emergency Shutdown (ESD) Response",
    category: "Operations",
    version: "v4.3",
    department: "Operations",
    approvedBy: "Robert Singh",
    lastReviewed: "2026-02-28",
    status: "active",
  },
  {
    id: "sop-6",
    code: "SOP-MNT-0115",
    title: "Compressor Alignment & Balancing",
    category: "Maintenance",
    version: "v1.8",
    department: "Maintenance",
    approvedBy: "David Reyes",
    lastReviewed: "2026-01-15",
    status: "active",
  },
  {
    id: "sop-7",
    code: "SOP-HSE-0047",
    title: "Confined Space Entry Permit",
    category: "Safety",
    version: "v3.1",
    department: "HSE",
    approvedBy: "Lisa Park",
    lastReviewed: "2025-12-10",
    status: "archived",
  },
  {
    id: "sop-8",
    code: "SOP-TA-0009",
    title: "Turnaround Isolation Checklist",
    category: "Turnaround",
    version: "v1.0-draft",
    department: "Turnaround",
    approvedBy: "Sarah Mitchell",
    lastReviewed: "2026-06-25",
    status: "draft",
  },
];

export const AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "log-1",
    timestamp: "2026-07-01T08:42:00Z",
    user: "David Reyes",
    role: "Engineer",
    action: "Document viewed",
    resource: "SOP-MNT-0088 — Pump Seal Replacement",
    outcome: "success",
    ipAddress: "10.24.1.45",
  },
  {
    id: "log-2",
    timestamp: "2026-07-01T08:30:00Z",
    user: "Maria Chen",
    role: "Engineer",
    action: "Work order updated",
    resource: "WO-8842 — Cooling water pump overhaul",
    outcome: "success",
    ipAddress: "10.24.1.62",
  },
  {
    id: "log-3",
    timestamp: "2026-07-01T08:15:00Z",
    user: "Operator Guest",
    role: "Operator",
    action: "Search executed",
    resource: 'Query: "P-4102 seal replacement procedure"',
    outcome: "success",
    ipAddress: "10.24.2.18",
  },
  {
    id: "log-4",
    timestamp: "2026-07-01T07:55:00Z",
    user: "James Okonkwo",
    role: "Engineer",
    action: "Compliance report exported",
    resource: "OISD Q2 Audit Summary",
    outcome: "success",
    ipAddress: "10.24.1.88",
  },
  {
    id: "log-5",
    timestamp: "2026-07-01T07:40:00Z",
    user: "Unknown",
    role: "Viewer",
    action: "Access denied",
    resource: "/settings — Admin settings",
    outcome: "denied",
    ipAddress: "10.24.3.12",
  },
  {
    id: "log-6",
    timestamp: "2026-07-01T07:22:00Z",
    user: "Lisa Park",
    role: "Engineer",
    action: "SOP approved",
    resource: "SOP-HSE-0031 — LOTO Procedure v5.0",
    outcome: "success",
    ipAddress: "10.24.1.71",
  },
  {
    id: "log-7",
    timestamp: "2026-07-01T06:50:00Z",
    user: "System",
    role: "System",
    action: "Document indexed",
    resource: "API-653-Tank-Inspection-T-401.pdf",
    outcome: "success",
    ipAddress: "127.0.0.1",
  },
  {
    id: "log-8",
    timestamp: "2026-07-01T06:30:00Z",
    user: "Robert Singh",
    role: "Operator",
    action: "Asset record viewed",
    resource: "P-4102 — Cooling Water Circulation Pump",
    outcome: "success",
    ipAddress: "10.24.2.44",
  },
  {
    id: "log-9",
    timestamp: "2026-07-01T06:10:00Z",
    user: "Sarah Mitchell",
    role: "Admin",
    action: "User role modified",
    resource: "j.okonkwo → Engineer",
    outcome: "warning",
    ipAddress: "10.24.1.10",
  },
  {
    id: "log-10",
    timestamp: "2026-07-01T05:45:00Z",
    user: "David Reyes",
    role: "Engineer",
    action: "Copilot query",
    resource: 'Query: "K-301 vibration history last 12 months"',
    outcome: "success",
    ipAddress: "10.24.1.45",
  },
];
