import type {
  KnowledgeDocument,
  SearchHistoryItem,
  SupportedFileType,
  UploadHistoryItem,
  UploadQueueItem,
} from "@/types/knowledge";

export const KNOWLEDGE_DOCUMENTS: KnowledgeDocument[] = [
  {
    id: "doc-001",
    title: "P&ID — Crude Distillation Unit 01",
    type: "P&ID",
    status: "indexed",
    version: "v3.2",
    owner: "Sarah Mitchell",
    department: "Engineering",
    lastUpdated: "2026-07-01T07:12:00Z",
    assetTag: "CDU-01",
    fileSize: "4.8 MB",
  },
  {
    id: "doc-002",
    title: "SOP — Pump P-4102 Seal Replacement",
    type: "SOP",
    status: "indexed",
    version: "v2.1",
    owner: "Maria Chen",
    department: "Maintenance",
    lastUpdated: "2026-06-30T16:40:00Z",
    assetTag: "P-4102",
    fileSize: "1.2 MB",
  },
  {
    id: "doc-003",
    title: "Inspection Report — Heat Exchanger E-2201",
    type: "Inspection Report",
    status: "review",
    version: "v1.0",
    owner: "James Okonkwo",
    department: "Reliability",
    lastUpdated: "2026-06-30T11:05:00Z",
    assetTag: "E-2201",
    fileSize: "2.4 MB",
  },
  {
    id: "doc-004",
    title: "OEM Manual — Centrifugal Compressor K-301",
    type: "OEM Manual",
    status: "indexed",
    version: "Rev. C",
    owner: "David Reyes",
    department: "Maintenance",
    lastUpdated: "2026-06-29T09:22:00Z",
    assetTag: "K-301",
    fileSize: "18.6 MB",
  },
  {
    id: "doc-005",
    title: "Incident Report — Unit 4 Flare Event",
    type: "Incident Report",
    status: "processing",
    version: "v1.0",
    owner: "Lisa Park",
    department: "HSE",
    lastUpdated: "2026-06-28T14:18:00Z",
    assetTag: "FLARE-04",
    fileSize: "890 KB",
  },
  {
    id: "doc-006",
    title: "API 510 Vessel Inspection — V-1204",
    type: "Inspection Report",
    status: "indexed",
    version: "v4.0",
    owner: "James Okonkwo",
    department: "Reliability",
    lastUpdated: "2026-06-28T08:30:00Z",
    assetTag: "V-1204",
    fileSize: "3.1 MB",
  },
  {
    id: "doc-007",
    title: "LOTO Procedure — CDU Furnace Shutdown",
    type: "SOP",
    status: "indexed",
    version: "v5.3",
    owner: "Robert Singh",
    department: "Operations",
    lastUpdated: "2026-06-27T17:45:00Z",
    assetTag: "F-101",
    fileSize: "756 KB",
  },
  {
    id: "doc-008",
    title: "Turnaround Scope — Q3 2026",
    type: "Engineering Drawing",
    status: "review",
    version: "v2.0",
    owner: "Sarah Mitchell",
    department: "Turnaround",
    lastUpdated: "2026-06-27T10:00:00Z",
    fileSize: "12.4 MB",
  },
  {
    id: "doc-009",
    title: "Cooling Water Pump Overhaul — WO-8842",
    type: "Maintenance Log",
    status: "indexed",
    version: "v1.2",
    owner: "Maria Chen",
    department: "Maintenance",
    lastUpdated: "2026-06-26T15:20:00Z",
    assetTag: "P-2208",
    fileSize: "445 KB",
  },
  {
    id: "doc-010",
    title: "NFPA 70E Electrical Safety Program",
    type: "Safety Manual",
    status: "indexed",
    version: "v3.0",
    owner: "Lisa Park",
    department: "HSE",
    lastUpdated: "2026-06-25T09:00:00Z",
    fileSize: "2.8 MB",
  },
  {
    id: "doc-011",
    title: "P&ID — Hydrogen Plant Reforming Section",
    type: "P&ID",
    status: "archived",
    version: "v2.8",
    owner: "David Reyes",
    department: "Engineering",
    lastUpdated: "2026-05-14T11:30:00Z",
    assetTag: "H2-REF",
    fileSize: "6.2 MB",
  },
  {
    id: "doc-012",
    title: "Flare Stack Maintenance History — Unit 4",
    type: "Maintenance Log",
    status: "indexed",
    version: "v1.5",
    owner: "Robert Singh",
    department: "Operations",
    lastUpdated: "2026-06-24T13:10:00Z",
    assetTag: "FLARE-04",
    fileSize: "1.1 MB",
  },
  {
    id: "doc-013",
    title: "EPA SPCC Plan — Tank Farm Area",
    type: "Safety Manual",
    status: "indexed",
    version: "v6.1",
    owner: "Lisa Park",
    department: "HSE",
    lastUpdated: "2026-06-22T08:55:00Z",
    fileSize: "5.5 MB",
  },
  {
    id: "doc-014",
    title: "Compressor K-301 Vibration Analysis",
    type: "Inspection Report",
    status: "failed",
    version: "v1.0",
    owner: "David Reyes",
    department: "Reliability",
    lastUpdated: "2026-06-20T16:00:00Z",
    assetTag: "K-301",
    fileSize: "980 KB",
  },
  {
    id: "doc-015",
    title: "CDU Furnace Tube Inspection Checklist",
    type: "SOP",
    status: "indexed",
    version: "v1.4",
    owner: "Maria Chen",
    department: "Maintenance",
    lastUpdated: "2026-06-19T10:30:00Z",
    assetTag: "F-101",
    fileSize: "620 KB",
  },
  {
    id: "doc-016",
    title: "Emergency Response Plan — Northfield Refinery",
    type: "Safety Manual",
    status: "indexed",
    version: "v7.0",
    owner: "Lisa Park",
    department: "HSE",
    lastUpdated: "2026-06-15T14:00:00Z",
    fileSize: "8.3 MB",
  },
];

export const SUPPORTED_FILE_TYPES: SupportedFileType[] = [
  { extension: "pdf", label: "PDF Documents", maxSizeMb: 50 },
  { extension: "dwg", label: "AutoCAD Drawings", maxSizeMb: 100 },
  { extension: "dxf", label: "DXF Drawings", maxSizeMb: 100 },
  { extension: "xlsx", label: "Excel Spreadsheets", maxSizeMb: 25 },
  { extension: "docx", label: "Word Documents", maxSizeMb: 25 },
  { extension: "png", label: "PNG Images", maxSizeMb: 15 },
  { extension: "tiff", label: "TIFF Scans", maxSizeMb: 30 },
  { extension: "msg", label: "Outlook Messages", maxSizeMb: 10 },
];

export const INITIAL_UPLOAD_QUEUE: UploadQueueItem[] = [
  {
    id: "uq-1",
    fileName: "API-653-Tank-Inspection-T-401.pdf",
    fileSize: "3.4 MB",
    fileType: "pdf",
    status: "processing",
    progress: 78,
    message: "OCR extraction in progress",
  },
  {
    id: "uq-2",
    fileName: "P-4102-Seal-Kit-BOM.xlsx",
    fileSize: "245 KB",
    fileType: "xlsx",
    status: "uploading",
    progress: 42,
  },
];

export const UPLOAD_HISTORY: UploadHistoryItem[] = [
  {
    id: "uh-1",
    fileName: "Turnaround-Scope-Q3-2026.pdf",
    fileType: "pdf",
    uploadedBy: "Sarah Mitchell",
    uploadedAt: "2026-06-30T15:30:00Z",
    status: "indexed",
    documentsCreated: 1,
  },
  {
    id: "uh-2",
    fileName: "CDU-01-PID-Rev32.dwg",
    fileType: "dwg",
    uploadedBy: "David Reyes",
    uploadedAt: "2026-06-29T11:15:00Z",
    status: "indexed",
    documentsCreated: 1,
  },
  {
    id: "uh-3",
    fileName: "Flare-Inspection-Photos.zip",
    fileType: "zip",
    uploadedBy: "Robert Singh",
    uploadedAt: "2026-06-28T09:00:00Z",
    status: "failed",
    documentsCreated: 0,
  },
  {
    id: "uh-4",
    fileName: "K-301-OEM-Manual-RevC.pdf",
    fileType: "pdf",
    uploadedBy: "Maria Chen",
    uploadedAt: "2026-06-27T14:45:00Z",
    status: "indexed",
    documentsCreated: 1,
  },
  {
    id: "uh-5",
    fileName: "LOTO-Procedure-F101.docx",
    fileType: "docx",
    uploadedBy: "James Okonkwo",
    uploadedAt: "2026-06-26T08:20:00Z",
    status: "indexed",
    documentsCreated: 1,
  },
];

export const SEARCH_HISTORY: SearchHistoryItem[] = [
  {
    id: "sh-1",
    query: "P-4102 seal replacement procedure",
    resultCount: 12,
    searchedAt: "2026-07-01T08:15:00Z",
  },
  {
    id: "sh-2",
    query: "CDU furnace tube inspection interval",
    resultCount: 8,
    searchedAt: "2026-06-30T19:42:00Z",
  },
  {
    id: "sh-3",
    query: "Flare stack maintenance history Unit 4",
    resultCount: 15,
    searchedAt: "2026-06-30T14:08:00Z",
  },
  {
    id: "sh-4",
    query: "API 653 tank inspection checklist",
    resultCount: 6,
    searchedAt: "2026-06-29T10:33:00Z",
  },
  {
    id: "sh-5",
    query: "NFPA 70E electrical safety",
    resultCount: 9,
    searchedAt: "2026-06-28T16:20:00Z",
  },
];

export const MAX_UPLOAD_SIZE_MB = 100;
