"""investigations

Create the ``investigations`` table backing ``InvestigationRecord``.

The model existed since the RCA/experience-replay work but was never
mapped onto ``Base``, so no table was ever autogenerated for it and
every ``ExperienceReplayService`` query failed at runtime.

Revision ID: 017_investigations
Revises: a276b1ad0f18
Create Date: 2026-08-19

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '017_investigations'
down_revision: Union[str, None] = 'a276b1ad0f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'investigations',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('conversation_id', sa.String(length=50), nullable=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('problem', sa.Text(), nullable=False),
        sa.Column('root_cause', sa.Text(), nullable=False),
        sa.Column('actions', sa.Text(), nullable=False),
        sa.Column('evidence_summary', sa.Text(), nullable=False),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.Column('failure_reason', sa.Text(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column(
            'confidence_evolution',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            'citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
        ),
        sa.Column(
            'graph_citations',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            'tools_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
        ),
        sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_investigations_conversation_id'),
        'investigations',
        ['conversation_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_investigations_user_id'),
        'investigations',
        ['user_id'],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f('ix_investigations_user_id'), table_name='investigations')
    op.drop_index(
        op.f('ix_investigations_conversation_id'), table_name='investigations',
    )
    op.drop_table('investigations')
