"""Sync models with database schema — realign indexes and constraints

Revision ID: 15910303c2ce
Revises: 014_conversations
Create Date: 2026-07-17 10:15:48.588379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '15910303c2ce'
down_revision: Union[str, None] = '014_conversations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_versions_latest'), table_name='document_versions', postgresql_where='(is_latest IS TRUE)')
    op.drop_index(op.f('ix_documents_active_listing'), table_name='documents', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_equipment_ids_gin'), table_name='documents', postgresql_using='gin')
    op.drop_index(op.f('ix_ingestion_jobs_polling'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_polling'), 'ingestion_jobs', ['status', 'next_retry_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_documents_equipment_ids_gin'), 'documents', ['equipment_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_active_listing'), 'documents', ['created_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_document_versions_latest'), 'document_versions', ['document_id'], unique=False, postgresql_where='(is_latest IS TRUE)')
    # ### end Alembic commands ###
