"""add_category

Revision ID: a276b1ad0f18
Revises: 016_conversation_persistence
Create Date: 2026-07-20 09:07:46.755343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a276b1ad0f18'
down_revision: Union[str, None] = '016_conversation_persistence'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_conv_turn'), table_name='conversation_snapshots')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.add_column('memories', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('memories', sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('memories', sa.Column('relationships', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_memories_user_type'), table_name='memories')
    op.drop_constraint(op.f('memories_user_id_fkey'), 'memories', type_='foreignkey')
    op.create_foreign_key(None, 'memories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.create_foreign_key(op.f('memories_user_id_fkey'), 'memories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_memories_user_type'), 'memories', ['user_id', 'type'], unique=False)
    op.drop_column('memories', 'relationships')
    op.drop_column('memories', 'entities')
    op.drop_column('memories', 'category')
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_snapshots_conv_turn'), 'conversation_snapshots', ['conversation_id', 'turn_index'], unique=True)
    # ### end Alembic commands ###
